name: build2

on:
  workflow_dispatch:
jobs:
  build2:
    runs-on: ubuntu-latest
    steps:
      # 下载目标文件
      - name: Download
        run: |
          curl -L -o Polaris-Obfuscators.zip "https://github.com/x20888450/Polaris-Obfuscators/releases/download/v1.0/clang.zip"
          unzip clang.zip -d clang
          ./clang/clang -mllvm -passes=fla,indcall ./examples/1/example1.cpp -o test
