name: build2

on:
  push:
  workflow_dispatch:

jobs:
  build2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Download and Extract Clang
        run: |
          curl -L -o clang.zip "https://github.com/x20888450/Polaris-Obfuscators/releases/download/v1.0/clang.zip"
          if [ $? -ne 0 ]; then echo "下载 Clang 失败"; exit 1; fi
          unzip clang.zip -d clang

      - name: List files in clang folder
        run: |
          ls -l clang

      - name: Replace NDK Clang
        run: |
          if [ -z "$ANDROID_NDK" ]; then
            echo "ANDROID_NDK 环境变量未设置，请检查环境配置。" && exit 1
          fi
          NDK_BIN="$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin"
          sudo cp clang/clang "$NDK_BIN/clang"
          sudo cp clang/clang++ "$NDK_BIN/clang++"
          sudo chmod +x "$NDK_BIN/clang" "$NDK_BIN/clang++"

      - name: Build with Clang
        run: |
          clang++ ./examples/2/example2.cpp -o test
