name: build

on:
  # 手动触发构建工作流
  workflow_dispatch:
    inputs:
      release:
        description: '是否发布新版本'
        required: false
        default: 'false' # 默认不发布新版本
      version:
        description: '发布版本号'
        required: false
        default: 'v1.0' # 默认版本号为 v1.0

jobs:
  build-project:
    runs-on: ubuntu-latest # 使用最新版本的 Ubuntu 运行器

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1 # 拉取代码仓库内容

      - name: CMake build
        # 安装 Ninja 构建工具并运行自定义构建脚本 build.sh
        run: sudo apt-get install ninja-build && chmod +x build.sh && ./build.sh

     # - name: Upload Build Artifacts
       # uses: actions/upload-artifact@v4
      #  with:
        #  name: Polairs-Obfuscator # 上传的构建产物名称
        #  path: src/build          # 指定构建产物路径
       #   retention-days: 30       # 设置存储天数为 30 天

      - name: Upload release
        # 仅在以下条件满足时发布新版本：
        # 1. 手动触发输入参数 release 设置为 'true'
        # 2. 构建成功
        # 3. 工作流未被取消
        if: github.event.inputs.release == 'true' && success() && !cancelled()
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 的身份验证令牌
          name: ${{ github.event.inputs.version }} # 发布版本名称
          tag: ${{ github.event.inputs.version }}  # 发布版本标签
          body: 这是通过 GitHub Actions 自动构建发布的版本。 # 发布描述
          artifacts: "/src"             # 包含的发布文件路径
          allowUpdates: true            # 允许更新已存在的发布
          makeLatest: true              # 将此发布标记为最新版本
          omitBodyDuringUpdate: true    # 更新时省略正文内容
          replacesArtifacts: true       # 更新时替换发布中的文件
