name: build

on:
  #push:
  workflow_dispatch:

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: CMake build
        run: sudo apt-get install ninja-build && chmod +x build.sh && ./build.sh

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: src/build
          retention-days: 30
